# Generated by Django 5.0.6 on 2026-06-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='orders_orde_mpesa_c_9863bb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid'], name='orders_orde_paid_34f5f6_idx'),
        ),
    ]
